name: CMake

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest

      - name: CMake - Configure
        run: cmake -B build/
      - name: CMake - Build
        run: cmake --build build/ --parallel
      - name: CMake - Test
        run: cmake --build build/ --target unittest
      - name: CMake - Run benchmark (dbg mode)
        run: cmake --build build/ --target bench
      - name: CMake - Run benchmark-mimalloc (dbg mode)
        run: cmake --build build/ --target bench_mimalloc
